server:
  port: 8080
spring:
  datasource:
    name: spring_mybatis
#     type: com.alibaba.druid.pool.DruidDataSource
    master:
          driver-class-name: com.mysql.jdbc.Driver
          jdbcurl: jdbc:mysql://localhost/mytest?userUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: 123456
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/wang_shiwei?userUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
    read: get,select,count,list,query,find
    write: add,create,update,delete,remove,insert
    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost/mytest?userUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
#      username: root
#      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 20000
      filters: stat
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      validation-query: select 'x'
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wsw.springmybatisdemo.pojo
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  returnPageInfo: check


